import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { Toaster } from "sonner";
import { NotificationProvider } from "@/contexts/notification-context";
import { ClientSessionProvider } from "@/components/providers/client-session-provider";
import { ThemeProvider } from "@/components/providers/theme-provider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()


  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ClientSessionProvider session={session}>
            <NotificationProvider>
              <Toaster position="top-right" richColors />
              {children}
            </NotificationProvider>
          </ClientSessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
